/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import java.sql.*;
import Controle.Bd_Conexao;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;


/**
 *
 * @author ramon
 */
public class Login extends javax.swing.JFrame {

    TelaPrincipalPaciente formTelaPrincipalPaciente = new TelaPrincipalPaciente();
    TelaPrincipalFarmaceutico formTelaPrincipalFarmaceutico = new TelaPrincipalFarmaceutico();
    TelaPrincipalMedico formTelaPrincipalMedico = new TelaPrincipalMedico();
    TelaPrincipalAdministrador formTelaPrincipalAdministrador = new TelaPrincipalAdministrador();
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
        
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          status();     
    }
    
    
     /**
     * Método responsável por exibir o ícone de status da conexão
     */
    private void status() {
        try {
            conexao = Bd_Conexao.conectar();
            if (conexao != null) {
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/figuras/dbok.png")));
            } else {
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/figuras/dberror.png")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conexao.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    /**
     * Método responsável pela autenticação e gestão de perfil do usuário     
     */
    private void logar() {        
        //String sql = "select * from tb_usuarios where login = ? and senha = md5(?)";
       
        String sql = "SELECT * FROM tb_usuarios WHERE login=? AND senha=?";
        
        try {
            conexao = Bd_Conexao.conectar();
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jTextField1.getText());
            String captura = new String(jPasswordField1.getPassword());
            pst.setString(2, captura);
            
            rs = pst.executeQuery();
            
            boolean registro_vf = rs.next();
             //System.out.println(registro_vf);
            
            if (registro_vf) 
            {
                String perfil = rs.getString(4); //pega o perfil
                
                
                if (perfil.equals("Paciente")) 
                { 
                    int idf = rs.getInt(5);
                    formTelaPrincipalPaciente.SetIdPaciente(idf);                    
                    formTelaPrincipalPaciente.setVisible(true);                  
                    System.out.println("Paciente");
                    this.dispose(); //fecha a tela anterior                    
                } 
                else if(perfil.equals("Farmaceutico"))
                {
                    int idf = rs.getInt(7);
                    formTelaPrincipalFarmaceutico.SetIdFarmaceutico(idf);                    
                    formTelaPrincipalFarmaceutico.setVisible(true);                  
                    System.out.println("Faramaceutico");
                    this.dispose(); //fecha a tela anterior  
                }
                else if(perfil.equals("Medico"))
                {       
                    int idf = rs.getInt(6);
                    formTelaPrincipalMedico.SetIdMedico(idf);                    
                    formTelaPrincipalMedico.setVisible(true);                   
                    System.out.println("Medico");
                    this.dispose();
                }
                else if(perfil.equals("Administrador"))
                {       
                    int idf = rs.getInt(6);
                    //formTelaPrincipalAdministrador.SetIdMedico(idf);                    
                    formTelaPrincipalAdministrador.setVisible(true);                   
                    System.out.println("Administrador");
                    this.dispose();
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s)");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conexao.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    } 
       
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btLogar = new javax.swing.JButton();
        btRecuperarSenha1 = new javax.swing.JButton();
        btNovoUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setName(""); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 188, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 188, -1));

        btLogar.setText("Logar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, -1));

        btRecuperarSenha1.setText("Recuperar Senha");
        btRecuperarSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecuperarSenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(btRecuperarSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, -1));

        btNovoUsuario.setText("Novo Usuário");
        btNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btNovoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, -1));

        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/figuras/back_verde_login.jpg"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoUsuarioActionPerformed
        // TODO add your handling code here:
        Cadastro form = new Cadastro(); // Crie uma instância do Form2
        form.setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_btNovoUsuarioActionPerformed

    private void btRecuperarSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecuperarSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRecuperarSenha1ActionPerformed

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
       
        logar();        
      
    }//GEN-LAST:event_btLogarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogar;
    private javax.swing.JButton btNovoUsuario;
    private javax.swing.JButton btRecuperarSenha1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
